name: method_channel_app
description: A simple Flutter app demonstrating MethodChannel with native Android (Java).
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/screenshot.png
